### ISSUE TITLE
Update Fees to Use 2018 Impact Fee Schedule

### ISSUE THREAD

**Issue by mikewynne** [sfcpc/ifc#142]
The 2018 impact fee schedule went into effect on Jan 1, 2018.  The tool needs to be updated to include these.
http://forms.sfplanning.org/Impact_Fee_Schedule_2018.pdf

**Comment by adamlodge** [comment]
For keeping track of which fees are updated in the branch

- [ ] Balboa Park Infrastructure
- [ ] Citywide Childcare Residential
- [ ] downtown park fee
- [ ] market octavia affordable housing
- [ ] rincon hill infrastructure
- [ ] soma community stabelization
- [ ] soma non-residential open space
- [ ] transit center open space
- [ ] transit center transportation
- [ ] van ness market infrastructure
- [ ] van ness market affordable housing
- [ ] visitacion valley infrasturcture

**Comment by adamlodge** [comment]
@mikewynne I didnt see any reference to the Citywide residential Child Care Impact Fee in the 2018 fee schedule document provided at the top of this ticket.  Can I assume that no fee index adjustment is necessary?

**Comment by adamlodge** [comment]
@mikewynne - all of these fees are now updated.  The process for updating was less than optimal given that you'll have to do this on a yearly basis.  I created a new ticket to streamline the process here #151 .

**Comment by mikewynne** [comment]
@adamlodge Thanks Adam!  Did you find the Child Care - Residential?  Looks like it's about half way down page 2 of the PDF:
![child2018](https://user-images.githubusercontent.com/7946733/37309117-2a403120-25fd-11e8-8aa5-468bc5d5ebc3.PNG)
