### ISSUE TITLE
General UI Changes

### ISSUE THREAD

**Issue by mikewynne** [sfcpc/ifc#143]
Various UI issues:
- [ ] All GSF numbers should have commas to be easier to read.
- [ ] Use placeholder text to add explanations to the input fields as can be confusing distinguishing similar terms (e.g. removed versus replaced, new versus net new, etc.).
- [ ] Need buttons (calculate, next, report, etc.) on the bottom of the page so planners don’t have to scroll back up.  More intuitive to have them at the bottom.
- [ ] FAR should always resolve to 1 - e.g. 5.45:1 rather than 60:11.
- [ ] In final report, list all impact fees - those with a fee due, those not triggered, and also those not built out in the calculator.
- [ ] On the output page, could we hyperlink the fee Code Sections within each of the Fee names listed? That way if there’s any confusion, folks can drill into the Code really easily.
- [ ] Import record name from Accela PPTS if person searches by planning application number [MW: the record name is returned by the geocoding service].  Or, just have an input box so that the user can type a name.
- [ ] Change GSF to GFA to be consistent with the terminology used in the Planning Code
- [ ] Generally order inputs as Existing followed by Removed followed by New
- [ ] On home page change 'Change Of Use' to 'Change of Use or Replacement of Use'

**Comment by adamlodge** [comment]
@robgaston - I'll leave it to you to decide if you want to split these into seperate tickets.  I can imagine wanting to do some if some of these are significant effort while others are trivial in order to take that into consideration as we prioritize work.

**Comment by adamlodge** [comment]
All but the two unchecked are resolved.  Those two have been seperated out into their own tickes #148 and #149.
