### ISSUE TITLE
Updated all fees to match the new - 2019 fee schedule

### ISSUE THREAD

**Issue by mikewynne** [sfcpc/ifc#206]
All fees are increasing by 6% and are detailed in the new fee schedule which goes live on Jan 1, 2019.  The Fee Schedule is available on this page:  https://sf-planning.org/impact-fees.  
Direct link is here: http://forms.sfplanning.org/Impact_Fee_Schedule_2019_notification.pdf

**Comment by robgaston** [comment]
- [ ] affordable housing
- [ ] balboa park infrastructure
- [ ] bicycle parking in lieu
- [ ] downtown park fee
- [ ] downtown special development district open space
- [ ] eastern neighborhoods infrastructure
- [ ] eastern neighborhoods non residential open space
- [ ] eastern neighborhoods residential open space
- [ ] citywide childcare hotel office
- [ ] jobs housing linkage
- [ ] market octavia affordable housing
- [ ] market octavia infrastructure
- [ ] public art
- [ ] citywide childcare residential
- [ ] rincon hill infrastructure
- [ ] soma community stabilization fee
- [ ] soma non residential open space
- [ ] transit center open space
- [ ] transit center transportation
- [ ] transportation sustainability fee
- [ ] van ness market infrastructure
- [ ] visitacion valley infrastructure

**Comment by robgaston** [comment]
@mikewynne looking [here](http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_425), it appears that the "soma non residential open space" has been repealed. should we remove this fee?

**Comment by mikewynne** [comment]
@robgaston It looks like it was repealed as part of the Central SoMa plan adoption, but I'm not sure what, if anything, replaced it, so let me confirm with Corey and get back to you.

**Comment by robgaston** [comment]
@mikewynne by the way, you may have noticed that I added a new team member to the project.  My new Farallon colleague, @njkim (Namjun), has been kind enough to lend a needed hand on this work, FYI. (thanks, @njkim!)

**Comment by mikewynne** [comment]
@njkim Hi Namjun, nice to e-meet you!

**Comment by njkim** [comment]
@mikewynne Nice to meet you too, Mike. Glad I could help.

**Comment by mikewynne** [comment]
@robgaston Can you please check the Jobs-Housing fee.  For Change of Use for PDR with cert of occupancy prior to April 1, 2010, I think it's using the details from the planning code rather than the fee schedule.  This one is particularly confusing as the code states that entertainment, hotel, etc. should use the new construction fee minus $14.09, which I think is what you did.  Page 7 of the fee schedule lists out the fees per use for the changes of use, and we should be using those fees, e.g. for PDR to Entertainment it should be $7.03 per GFA, the tool is currently showing $12.57.

**Comment by mikewynne** [comment]
@robgaston Just to confirm - the soma non residential open space fee has definitely been repealed, so please delete it.  Thanks

**Comment by robgaston** [comment]
@mikewynne I addressed both of your comments above in the latest.  Thanks!
