### ISSUE TITLE
Add Fee Type: Affordable Housing Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#51]
Affordable Housing Fee

citywide scope

Planning Code Section 415
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_415

This fee addresses the impact created by new market-rate housing to the stock of, and need for, affordable housing. It applies city-wide to residential projects and is triggered by the creation of ten or more dwelling units. Generally, the fee is calculated based on twenty percent of the number of proposed units, at a unit-size mix reflective of the overall project. There are additional options for compliance with this fee, including providing affordable units on or off-site.

NOTE: Affordable Housing fees may soon all change their logic (switching from unit based to square footage based), so hold off on these for now (don't start without confirmation on the logic change).

**Comment by mikewynne** [comment]
The new logic has just been published for this fee.  Starting January 1, 2019, the fee will be applied on per square foot basis, rather than on the current per unit basis. Details are shown on the Inclusionary Housing page here: https://sf-planning.org/inclusionary-affordable-housing-program.  It'll be published on the Planning Code in Jan.

**Comment by mikewynne** [comment]
@robgaston The fee is calculating perfectly.  But, given that this fee may be paid or bypassed by building affordable housing, can we add a checkbox to say 'Project fulfills affordable housing requirements', which will result in the fee not being calculated.  I'm going to meet with the affordable housing group to see if they want anything added to the IFC for projects that are partly met by the fee payment and partly meet by building affordable housing.

**Comment by robgaston** [comment]
@mikewynne I added the checkbox that you described above in #215 

Thanks!

**Comment by mikewynne** [comment]
@robgaston Thanks!

**Comment by mikewynne** [comment]
@robgaston I'm going to close this for now, although we might reopen it next week if the affordable housing team decide that they want to enhance it.

**Comment by mikewynne** [comment]
Hey @robgaston Can you look at the tables in the PDF below, it includes is a detailed description of how to calculate the affordable housing fees (this inclusionary fee and the UMU fee).  To me it looks too crazily complex to build our in these fees in the time that we have left, so I'm thinking that we should maybe just do a totally dumbed down version of just sending the user to this doc and getting them to enter the percentage.  Can you let me know what you think?  Thanks, Mike

http://forms.sfplanning.org/Inclusionary_Affordable_Housing_Affidavit.pdf

**Comment by mikewynne** [comment]
@robgaston Hey Rob, I'm going to take a shot at tweaking this and the UMU fees, I might pass it back if it gets too tricky. :)

**Comment by robgaston** [comment]
@mikewynne sorry for the delay on my end!  Looks like you got this one handled in a way that didn't require too much fuss, which is great.  Let me know if you still need any help here
