### ISSUE TITLE
Add Fee Type: Child Care Fee: Office/Hotel Projects

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#52]
citywide scope

This fee addresses the impact created by certain employment- generating uses on the availability of child care. It applies city-wide to office and hotel projects and is triggered by the creation of 25,000 square feet or more of office or hotel uses. There are additional options for compliance with this fee, including the provision of on or off-site child care.

http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_414

**Comment by ryan86** [comment]
Hi @mikewynne do you have an ArcGIS layer(s) that excludes or otherwise isolates the areas listed in 414.3b?

http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_414.3

**Comment by ryan86** [comment]
@mikewynne I made the assumption that the cases outlined in 414.5-414.7 can be combined because I think they are effectively the same as far as the fee calculator is concerned.

**Comment by mikewynne** [comment]
@ryan86 We can just ignore 4143.b, staff should that the fee doesn't apply to those sites.

**Comment by mikewynne** [comment]
@ryan86 Yeah, feel free to combine them (414.5-7).

**Comment by robgaston** [comment]
@ryan86 I made some fixes in the above commit (a7ea2b3)

I noticed that the fee can turn up negative here, which is probably not what we want.  I think the logic will need some adjustment.

**Comment by mikewynne** [comment]
I confirmed with Corey that the fee is good.
