### ISSUE TITLE
Add Fee Type: Child Care Fee: Residential Projects

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#53]
Child Care Fee: Residential Projects
Planning Code Section 414A

http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_414A

citywide scope

This fee addresses the impacts of increased residential population on the demand for additional child care services. It applies city-wide to almost all residential projects and is triggered by (1) the creation of at least one new dwelling unit, (2) the creation of new group housing or residential care facilities, and (3) additions to any existing residential uses of more than 800 gross square feet. There are additional options for compliance with this fee, including the provision of on-site Designated Child Care Units through an in-kind agreement. Additionally, this fee may be reduced if a project is also subject to an impact fee that dedicates a portion of that fee to child care.

**Comment by mikewynne** [comment]
We have had multiple people report that the fee is calculating correctly but Corey said the fee was incorrect for 1 Oak St.  I'll follow up with him to clarify.

**Comment by mikewynne** [comment]
Change the "New Construction" field in the Calculate page to "New Construction or Addition".

Two changes related to the credits (in the Calculate page):
1. Change from a percentage to an actual value.
2. Have two credit fields - one for New Construction or Addition and one for "Change of Use" (right now we just have a field for change of use).

Other than those minor changes, the field is calculating correctly.

**Comment by mikewynne** [comment]
@robgaston The fee looks good, thanks!
