### ISSUE TITLE
Add Fee Type: Jobs-Housing Linkage Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#54]
Planning Code Section 413
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_413

This fee addresses the impact created by employment- generating uses to the availability of affordable housing. It applies city-wide to most non-residential uses and is triggered by the creation of at least 25,000 square feet. In the case of a change of use, fees are lowered to provide credit for the exist- ing use. There are additional options for compliance with this fee, including an in-lieu payment to a housing developer.

citywide scope

**Comment by robgaston** [comment]
@jmunowitch  I fixed a label in #182 

otherwise this looks good to me; assigning to @mikewynne to QA fee calculation

**Comment by mikewynne** [comment]
A couple of minor issues:

1. Can we please copy the hotel and office GFA from the trigger page to the calculation page.  I know it's duplicative but it's a little confusing seeing all of the other land use types but not the hotel and office (users were incorrectly thinking that they had been missed).

2. The hotel GFA is always showing as 0 in the report page.  The fee is calculating correctly, so it's just a UI issue.

**Comment by mikewynne** [comment]
@robgaston I just assigned this to you although I wasn't sure if this should go back to you or @jmunowitch

**Comment by mikewynne** [comment]
@robgaston These changes look good, thanks.  One more thing though,  It looks like only half of the fee has been built out - it handles New Construction/Additions fine (code section 413.6A) but seems to miss out Replacement of Use/Change of Use (code section 413.6B).

**Comment by robgaston** [comment]
@mikewynne change & replacement of use have been added here

**Comment by mikewynne** [comment]
@robgaston We may still have an issue with the change/replacement of use.  If we look at an example of a 20K office being demolished and replaced by a new 100K office building. We put in 100K of new construction and 20K of replacement and 80K as the increase in non-res GFA. See link below for an example. We expected that to result in a fee where 80K goes towards the new construction and 20K goes to replacement of use, but the IFC shows 100K going to new construction and 20K going to replacement of use.  Can you let me know if that's an IFC issue or more of a training issue with how we filled out the trigger page?  Thanks.  If it's easier we could set up a call between us and Corey to chat about it.

https://sfcpc.github.io/ifc/?state=trigger&fees=%7B%22citywide-childcare-residential%22%3A%7B%22newConstructionCredit%22%3Anull%2C%22changeOfUseCredit%22%3Anull%7D%2C%22citywide-childcare-hotel-office%22%3A%7B%22ccfGFA%22%3A%220%22%2C%22minCcfGFARequired%22%3A10000%2C%22totalProjGFA%22%3A%22100000%22%7D%2C%22eastern-neighborhoods-infrastructure%22%3A%7B%22nonResToResEN%22%3Anull%2C%22pdrToResEN%22%3Anull%2C%22pdrToNonResEN%22%3Anull%2C%22nonResToResReplacement%22%3Anull%2C%22pdrToResReplacement%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22allAffordable%22%3Anull%7D%2C%22jobs-housing-linkage%22%3A%7B%22newEnt%22%3A%220%22%2C%22newIntegratedPDR%22%3A%220%22%2C%22newResearchAndDevelopment%22%3A%220%22%2C%22newRetail%22%3A%220%22%2C%22newSmallEnterpriseWorkspace%22%3A%220%22%2C%22feeCredit%22%3A%220%22%2C%22oldPDRToEnt%22%3A%220%22%2C%22oldPDRToHotel%22%3A%220%22%2C%22oldPDRToOffice%22%3A%2220000%22%2C%22oldPDRToIntegratedPDR%22%3A%220%22%2C%22oldPDRToResearchAndDevelopment%22%3A%220%22%2C%22oldPDRToRetail%22%3A%220%22%2C%22oldPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22newPDRToEnt%22%3A%220%22%2C%22newPDRToHotel%22%3A%220%22%2C%22newPDRToOffice%22%3A%220%22%2C%22newPDRToIntegratedPDR%22%3A%220%22%2C%22newPDRToResearchAndDevelopment%22%3A%220%22%2C%22newPDRToRetail%22%3A%220%22%2C%22newPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22resToEnt%22%3A%220%22%2C%22resToHotel%22%3A%220%22%2C%22resToOffice%22%3A%220%22%2C%22resToIntegratedPDR%22%3A%220%22%2C%22resToResearchAndDevelopment%22%3A%220%22%2C%22resToRetail%22%3A%220%22%2C%22resToSmallEnterpriseWorkspace%22%3A%220%22%7D%2C%22public-art%22%3A%7B%22constructionCost%22%3Anull%2C%22posRequirement%22%3Anull%2C%22nonResProject%22%3Anull%7D%2C%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22soma-non-residential-open-space%22%3A%7B%22newManufacturing%22%3Anull%2C%22paySomaFee%22%3Anull%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGFA%22%3Anull%7D%2C%22eastern-neighborhoods-non-residential-open-space%22%3A%7B%22pdrToNonResEN%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22retailOpenSpaceRequiredGFA%22%3Anull%2C%22retailOpenSpaceProvidedGFA%22%3Anull%2C%22manufacturingGFA%22%3Anull%2C%22manufacturingOpenSpaceRequiredGFA%22%3Anull%2C%22manufacturingOpenSpaceProvidedGFA%22%3Anull%2C%22officeOpenSpaceRequiredGFA%22%3Anull%2C%22officeOpenSpaceProvidedGFA%22%3Anull%2C%22otherGFA%22%3Anull%2C%22otherOpenSpaceRequiredGFA%22%3Anull%2C%22otherOpenSpaceProvidedGFA%22%3Anull%7D%2C%22eastern-neighborhoods-residential-open-space%22%3A%7B%22openSpaceProvidedGFA%22%3Anull%2C%22publiclyAccessible%22%3Anull%7D%2C%22downtown-special-development-district-open-space%22%3A%7B%22openSpaceProvidedGFA%22%3A%220%22%2C%22publiclyAccessible%22%3Anull%7D%7D&title=&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13627651.870911729%2C4547282.796830939%5D%2C%5B-13627659.47024809%2C4547265.893025621%5D%2C%5B-13627666.774699112%2C4547248.85855797%5D%2C%5B-13627673.782149743%2C4547231.698920976%5D%2C%5B-13627680.490039617%2C4547214.41890344%5D%2C%5B-13627686.89669895%2C4547197.024139122%5D%2C%5B-13627694.241781592%2C4547175.83379331%5D%2C%5B-13627748.400606295%2C4547197.0756824585%5D%2C%5B-13627750.905851435%2C4547231.582032692%5D%2C%5B-13627686.349897616%2C4547296.300742049%5D%2C%5B-13627651.870911729%2C4547282.796830939%5D%5D%5D%7D&newUnits=0&removedUnits=0&existingUnits=0&newNonRes=100000&nonResGFA=80000&pdrGFA=0&resGFA=0&changeOfUse=20000&officeGFA=100000&hotelGFA=0&firstConstructionDocument=&existingNonResGFA=20000&finalBuildingHeight=120&totalExistingGFA=200000&newRes=0&nonResToRes=0&pdrToRes=0&pdrToNonRes=20000&retailGFA=&institutionalGFA=&industrialGFA=&parcelArea=

**Comment by robgaston** [comment]
@mikewynne the new office value (100k in your example) is assumed by the application to be just the newly constructed office GFA; as such, we don't currently calculate the difference as you've described above.  I think in this example, you would need to input 80k for this value, but that being said we may be using this value incorrectly.  Should we instead add a separate value for "newly constructed" use types, or should we continue doing what we are now and consider it a training (and perhaps labeling) issue?

**Comment by mikewynne** [comment]
@robgaston I have a meeting scheduled with Corey tomorrow afternoon, I'll ask him which he prefers.

**Comment by mikewynne** [comment]
@robgaston For the previous example Corey is certain that staff would expect to enter 100K for new construction and 20K for replacement of use, with the 20K being part of the 100K new building.  So, ideally we'd change the fee to work from that expectation.  But, if there are multiple fees pulling from those fields that would need to be changed to do that then maybe we could get away with changing the labeling. Let me know what you think, and we can always set up a quick phone call with Corey if that would help given that this fee is particularly complicated.

**Comment by robgaston** [comment]
@mikewynne I've taken a stab at calculating the portions of use as you've described above.  I think that this is okay from the perspective of existing fees, as it only effects how this fee is calculated. 
 however, some of the values are used for other fees, so the planners will need to tell us if that is problematic w/re: fee calculation.

At any rate, please take a look at what I've done as of #201 and let me know what you think.

Thanks!

**Comment by mikewynne** [comment]
It looks like the trigger isn't working correctly.  In this example, an addition of 6,600 sq ft of retail, the fee shouldn't be triggering as it's below 25K sq ft, but it is being triggered.  

https://sfcpc.github.io/ifc/?state=report&fees=%7B%22affordable-housing%22%3A%7B%22ownershipType%22%3Anull%2C%22exemptFromAffordableHousingFee%22%3Anull%7D%2C%22bicycle-parking-in-lieu%22%3A%7B%22spacesInLieu%22%3A%220%22%7D%2C%22downtown-special-development-district-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3A%220%22%7D%2C%22eastern-neighborhoods-infrastructure%22%3A%7B%22nonResToResEN%22%3Anull%2C%22pdrToResEN%22%3Anull%2C%22pdrToNonResEN%22%3Anull%2C%22nonResToResReplacement%22%3Anull%2C%22pdrToResReplacement%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22allAffordable%22%3Anull%7D%2C%22eastern-neighborhoods-non-residential-open-space%22%3A%7B%22pdrToNonResEN%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22retailOpenSpaceGFAShortfall%22%3Anull%2C%22manufacturingOpenSpaceGFAShortfall%22%3Anull%2C%22officeOpenSpaceGFAShortfall%22%3Anull%2C%22otherOpenSpaceGFAShortfall%22%3Anull%7D%2C%22eastern-neighborhoods-residential-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22citywide-childcare-hotel-office%22%3A%7B%22ccfGFA%22%3Anull%2C%22minCcfGFARequired%22%3Anull%2C%22totalProjGFA%22%3Anull%7D%2C%22jobs-housing-linkage%22%3A%7B%22newEnt%22%3A%220%22%2C%22newIntegratedPDR%22%3A%220%22%2C%22newResearchAndDevelopment%22%3A%220%22%2C%22newRetail%22%3A%226600%22%2C%22newSmallEnterpriseWorkspace%22%3A%220%22%2C%22feeCredit%22%3A%220%22%2C%22oldPDRToEnt%22%3A%220%22%2C%22oldPDRToHotel%22%3A%220%22%2C%22oldPDRToOffice%22%3A%220%22%2C%22oldPDRToIntegratedPDR%22%3A%220%22%2C%22oldPDRToResearchAndDevelopment%22%3A%220%22%2C%22oldPDRToRetail%22%3A%220%22%2C%22oldPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22newPDRToEnt%22%3A%220%22%2C%22newPDRToHotel%22%3A%220%22%2C%22newPDRToOffice%22%3A%220%22%2C%22newPDRToIntegratedPDR%22%3A%220%22%2C%22newPDRToResearchAndDevelopment%22%3A%220%22%2C%22newPDRToRetail%22%3A%220%22%2C%22newPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22resToEnt%22%3A%220%22%2C%22resToHotel%22%3A%220%22%2C%22resToOffice%22%3A%220%22%2C%22resToIntegratedPDR%22%3A%220%22%2C%22resToResearchAndDevelopment%22%3A%220%22%2C%22resToRetail%22%3A%220%22%2C%22resToSmallEnterpriseWorkspace%22%3A%220%22%7D%2C%22public-art%22%3A%7B%22constructionCost%22%3Anull%2C%22posRequirement%22%3Anull%2C%22nonResProject%22%3Anull%7D%2C%22citywide-childcare-residential%22%3A%7B%22newConstructionCredit%22%3Anull%2C%22changeOfUseCredit%22%3Anull%7D%2C%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22soma-non-residential-open-space%22%3A%7B%22newManufacturing%22%3Anull%2C%22paySomaFee%22%3Anull%7D%2C%22transportation-sustainability-fee%22%3A%7B%22exemptFromTSF%22%3Anull%2C%22nonResNonHealthGFA%22%3A%226600%22%2C%22hospitalGFA%22%3A%220%22%2C%22healthGFA%22%3A%220%22%2C%22newNewHospitalBeds%22%3A%220%22%2C%22totalHospitalOperatorBeds%22%3A%220%22%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGFA%22%3Anull%7D%7D&title=&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13630223.800211882%2C4547189.234056621%5D%2C%5B-13630212.897246994%2C4547190.989627171%5D%2C%5B-13630206.756418604%2C4547152.807513296%5D%2C%5B-13630217.732965676%2C4547151.037725543%5D%2C%5B-13630223.800211882%2C4547189.234056621%5D%5D%5D%7D&newUnits=0&removedUnits=0&existingUnits=0&newNonRes=6600&nonResGFA=6600&pdrGFA=0&resGFA=0&changeOfUse=0&officeGFA=0&hotelGFA=0&existingNonResGFA=0&finalBuildingHeight=25&totalExistingGFA=0&newRes=&nonResToRes=&pdrToRes=&pdrToNonRes=&retailGFA=&institutionalGFA=&industrialGFA=&parcelArea=.
