### ISSUE TITLE
Add New Fee: Transportation Sustainability Fee (TSF)

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#58]
Transportation Sustainability Fee (TSF)
Planning Code Section 411A
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_411A

This fee addresses the impact created by all uses on the transportation system. It applies city-wide to all non-residential and PDR projects and large residential projects. It is triggered
by (1) construction of a new non-residential or PDR building, (2) additions and conversions to non-residential and PDR uses of varying sizes, or (3) the creation of 21 or more new dwelling units. In the case of a change of use, fees are lowered to provide credit for existing legal uses. The TSF replaces the TIDF (see above), which remains effective for grandfathered projects.

**Comment by robgaston** [comment]
@mikewynne I've merged an initial working version of this fee into `master`, but I find it likely that it will need some tweaks based on feedback from the planners.  Please take a look when you get a chance and let me know.

Thanks!

**Comment by mikewynne** [comment]
@robgaston I'm getting a NaN in the report when zero is entered for the hospital inputs.  There might also be something wrong with the 'non-res, 800-99,999gsf' section in the report - I enter zeros for everything non-res and get -800 in the report:

https://sfcpc.github.io/ifc/?state=trigger&fees=%7B%22affordable-housing%22%3A%7B%22ownershipType%22%3A%22rental%22%7D%2C%22bicycle-parking-in-lieu%22%3A%7B%22spacesInLieu%22%3A%2210%22%7D%2C%22downtown-special-development-district-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3A%22100%22%7D%2C%22eastern-neighborhoods-infrastructure%22%3A%7B%22nonResToResEN%22%3Anull%2C%22pdrToResEN%22%3Anull%2C%22pdrToNonResEN%22%3Anull%2C%22nonResToResReplacement%22%3Anull%2C%22pdrToResReplacement%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22allAffordable%22%3Anull%7D%2C%22eastern-neighborhoods-non-residential-open-space%22%3A%7B%22pdrToNonResEN%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22retailOpenSpaceGFAShortfall%22%3Anull%2C%22manufacturingOpenSpaceGFAShortfall%22%3Anull%2C%22officeOpenSpaceGFAShortfall%22%3Anull%2C%22otherOpenSpaceGFAShortfall%22%3Anull%7D%2C%22eastern-neighborhoods-residential-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22citywide-childcare-hotel-office%22%3A%7B%22ccfGFA%22%3Anull%2C%22minCcfGFARequired%22%3Anull%2C%22totalProjGFA%22%3Anull%7D%2C%22jobs-housing-linkage%22%3A%7B%22newEnt%22%3Anull%2C%22newIntegratedPDR%22%3Anull%2C%22newResearchAndDevelopment%22%3Anull%2C%22newRetail%22%3Anull%2C%22newSmallEnterpriseWorkspace%22%3Anull%2C%22feeCredit%22%3Anull%2C%22oldPDRToEnt%22%3Anull%2C%22oldPDRToHotel%22%3Anull%2C%22oldPDRToOffice%22%3Anull%2C%22oldPDRToIntegratedPDR%22%3Anull%2C%22oldPDRToResearchAndDevelopment%22%3Anull%2C%22oldPDRToRetail%22%3Anull%2C%22oldPDRToSmallEnterpriseWorkspace%22%3Anull%2C%22newPDRToEnt%22%3Anull%2C%22newPDRToHotel%22%3Anull%2C%22newPDRToOffice%22%3Anull%2C%22newPDRToIntegratedPDR%22%3Anull%2C%22newPDRToResearchAndDevelopment%22%3Anull%2C%22newPDRToRetail%22%3Anull%2C%22newPDRToSmallEnterpriseWorkspace%22%3Anull%2C%22resToEnt%22%3Anull%2C%22resToHotel%22%3Anull%2C%22resToOffice%22%3Anull%2C%22resToIntegratedPDR%22%3Anull%2C%22resToResearchAndDevelopment%22%3Anull%2C%22resToRetail%22%3Anull%2C%22resToSmallEnterpriseWorkspace%22%3Anull%7D%2C%22public-art%22%3A%7B%22constructionCost%22%3Anull%2C%22posRequirement%22%3Anull%2C%22nonResProject%22%3Anull%7D%2C%22citywide-childcare-residential%22%3A%7B%22newConstructionCredit%22%3A%220%22%2C%22changeOfUseCredit%22%3A%220%22%7D%2C%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22soma-non-residential-open-space%22%3A%7B%22newManufacturing%22%3Anull%2C%22paySomaFee%22%3Anull%7D%2C%22transportation-sustainability-fee%22%3A%7B%22exemptFromTSF%22%3Anull%2C%22nonResNonHealthGFA%22%3A%220%22%2C%22hospitalGFA%22%3A%220%22%2C%22healthGFA%22%3A%220%22%2C%22resToNonRes%22%3A%220%22%2C%22resToHealth%22%3A%220%22%2C%22resToHospital%22%3A%220%22%2C%22hospitalToRes%22%3A%220%22%2C%22hospitalToNonRes%22%3A%220%22%2C%22hospitalToPDR%22%3A%220%22%2C%22hospitalToHealth%22%3A%220%22%2C%22healthToRes%22%3A%220%22%2C%22healthToNonRes%22%3A%220%22%2C%22healthToPDR%22%3A%220%22%2C%22healthToHospital%22%3A%220%22%2C%22pdrToHealth%22%3A%220%22%2C%22pdrToHospital%22%3A%220%22%2C%22newNewHospitalBeds%22%3A%220%22%2C%22totalHospitalOperatorBeds%22%3A%220%22%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGFA%22%3Anull%7D%7D&title=&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13637002.320078615%2C4542712.379547522%5D%2C%5B-13637003.86296676%2C4542740.194390533%5D%2C%5B-13636991.370470867%2C4542740.893024877%5D%2C%5B-13636989.827360084%2C4542713.070015443%5D%2C%5B-13637002.320078615%2C4542712.379547522%5D%5D%5D%7D&newUnits=10&removedUnits=0&existingUnits=0&newNonRes=0&nonResGFA=0&pdrGFA=0&resGFA=100000&changeOfUse=0&officeGFA=0&hotelGFA=0&existingNonResGFA=0&finalBuildingHeight=100&totalExistingGFA=0&newRes=0&nonResToRes=0&pdrToRes=0&pdrToNonRes=0&retailGFA=&institutionalGFA=&industrialGFA=&parcelArea=

**Comment by mikewynne** [comment]
It looks pretty close but there may be something funky about the 'Non-Residential, all gsf above 99,999 gsf' section of the report.  In the example below we entered 140,000 non-res, so expected this to show 40,000, but it shows 90,001.

https://sfcpc.github.io/ifc/?state=report&fees=%7B%22affordable-housing%22%3A%7B%22ownershipType%22%3A%22rental%22%7D%2C%22bicycle-parking-in-lieu%22%3A%7B%22spacesInLieu%22%3A%222%22%7D%2C%22downtown-special-development-district-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3A%22100%22%7D%2C%22eastern-neighborhoods-infrastructure%22%3A%7B%22nonResToResEN%22%3A%220%22%2C%22pdrToResEN%22%3A%220%22%2C%22pdrToNonResEN%22%3A%220%22%2C%22nonResToResReplacement%22%3A%220%22%2C%22pdrToResReplacement%22%3A%220%22%2C%22pdrToNonResReplacement%22%3A%2250000%22%2C%22allAffordable%22%3Anull%7D%2C%22eastern-neighborhoods-non-residential-open-space%22%3A%7B%22pdrToNonResEN%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22retailOpenSpaceGFAShortfall%22%3A%220%22%2C%22manufacturingOpenSpaceGFAShortfall%22%3A%220%22%2C%22officeOpenSpaceGFAShortfall%22%3A%22100%22%2C%22otherOpenSpaceGFAShortfall%22%3A%220%22%7D%2C%22eastern-neighborhoods-residential-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22citywide-childcare-hotel-office%22%3A%7B%22ccfGFA%22%3A%220%22%2C%22minCcfGFARequired%22%3A14000%2C%22totalProjGFA%22%3A%22140000%22%7D%2C%22jobs-housing-linkage%22%3A%7B%22newEnt%22%3A%220%22%2C%22newIntegratedPDR%22%3A%220%22%2C%22newResearchAndDevelopment%22%3A%220%22%2C%22newRetail%22%3A%220%22%2C%22newSmallEnterpriseWorkspace%22%3A%220%22%2C%22feeCredit%22%3A%220%22%2C%22oldPDRToEnt%22%3A%220%22%2C%22oldPDRToHotel%22%3A%220%22%2C%22oldPDRToOffice%22%3A%2250000%22%2C%22oldPDRToIntegratedPDR%22%3A%220%22%2C%22oldPDRToResearchAndDevelopment%22%3A%220%22%2C%22oldPDRToRetail%22%3A%220%22%2C%22oldPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22newPDRToEnt%22%3A%220%22%2C%22newPDRToHotel%22%3A%220%22%2C%22newPDRToOffice%22%3A%220%22%2C%22newPDRToIntegratedPDR%22%3A%220%22%2C%22newPDRToResearchAndDevelopment%22%3A%220%22%2C%22newPDRToRetail%22%3A%220%22%2C%22newPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22resToEnt%22%3A%220%22%2C%22resToHotel%22%3A%220%22%2C%22resToOffice%22%3A%220%22%2C%22resToIntegratedPDR%22%3A%220%22%2C%22resToResearchAndDevelopment%22%3A%220%22%2C%22resToRetail%22%3A%220%22%2C%22resToSmallEnterpriseWorkspace%22%3A%220%22%7D%2C%22public-art%22%3A%7B%22constructionCost%22%3Anull%2C%22posRequirement%22%3Anull%2C%22nonResProject%22%3Anull%7D%2C%22citywide-childcare-residential%22%3A%7B%22newConstructionCredit%22%3A%220%22%2C%22changeOfUseCredit%22%3A%220%22%7D%2C%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22soma-non-residential-open-space%22%3A%7B%22newManufacturing%22%3Anull%2C%22paySomaFee%22%3Anull%7D%2C%22transportation-sustainability-fee%22%3A%7B%22exemptFromTSF%22%3Anull%2C%22nonResNonHealthGFA%22%3A%22140000%22%2C%22hospitalGFA%22%3A%220%22%2C%22healthGFA%22%3A%220%22%2C%22resToNonRes%22%3A%220%22%2C%22resToHealth%22%3A%220%22%2C%22resToHospital%22%3A%220%22%2C%22hospitalToRes%22%3A%220%22%2C%22hospitalToNonRes%22%3A%220%22%2C%22hospitalToPDR%22%3A%220%22%2C%22hospitalToHealth%22%3A%220%22%2C%22healthToRes%22%3A%220%22%2C%22healthToNonRes%22%3A%220%22%2C%22healthToPDR%22%3A%220%22%2C%22healthToHospital%22%3A%220%22%2C%22pdrToHealth%22%3A%220%22%2C%22pdrToHospital%22%3A%220%22%2C%22newNewHospitalBeds%22%3A%220%22%2C%22totalHospitalOperatorBeds%22%3A%220%22%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGFA%22%3Anull%7D%7D&title=&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13626055.101464119%2C4548431.141945683%5D%2C%5B-13626046.91792308%2C4548439.334789883%5D%2C%5B-13626033.278502464%2C4548452.989638434%5D%2C%5B-13626023.36728292%2C4548462.912087515%5D%2C%5B-13626013.456063379%2C4548472.834405204%5D%2C%5B-13626006.227086965%2C4548480.071359374%5D%2C%5B-13626027.940732885%2C4548502.028874193%5D%2C%5B-13626001.579164265%2C4548528.4200099595%5D%2C%5B-13625979.868635295%2C4548506.4594817%5D%2C%5B-13625959.5149796%2C4548485.87140529%5D%2C%5B-13626034.745136758%2C4548410.5569759635%5D%2C%5B-13626055.101464119%2C4548431.141945683%5D%5D%5D%7D&newUnits=140&removedUnits=0&existingUnits=0&newNonRes=140000&nonResGFA=90000&pdrGFA=0&resGFA=140000&changeOfUse=50000&officeGFA=140000&hotelGFA=0&existingNonResGFA=50000&finalBuildingHeight=120&totalExistingGFA=50000&newRes=140000&nonResToRes=0&pdrToRes=0&pdrToNonRes=50000&retailGFA=&institutionalGFA=&industrialGFA=&parcelArea=

**Comment by robgaston** [comment]
@mikewynne in the case you linked to above, it is using this value (90,001) is used as it is summing the new non-res (140,000) and the change of use (pdr to non-res; 50,000), so the value being calculated agains is 190,000.

Is this not how we should calculate this fee?

Thanks!

**Comment by mikewynne** [comment]
@robgaston I think this similar to the change of use issue that we saw in Jobs-Housing - the planners are expecting the change of use to be a subset of the new construction.  So they'd expect the total value to be 140k.

One more thing, the Non-Res, 800-99,999 gsf section in the report should really have 99,999 as the GFA to run the calculation.  I think you are removing the 800 from the total, but the fee is on the whole 99,999, the 800-99,999 is just the trigger.  Once they go over 800 they have to pay the fee on the whole site (no rebate for the first 800).  It might be worth changing the label in the report to say 'Non-Residential, up to 99,999 gsf' or something similar.

**Comment by robgaston** [comment]
@mikewynne I've incorporated the fixes that you've described in #214 

Thanks!

**Comment by mikewynne** [comment]
@robgaston I'm getting 99,199 for the GFA in the report for the non-res below 99,999 and then 40,801 for the above 99,999.  The 800 should be in the below 99,999 - so 99,999 in the first category and 40,001 in the second.

**Comment by robgaston** [comment]
@mikewynne good catch - fixed in #216 

Thanks!
