### ISSUE TITLE
Add Fee Type: Balboa Park Infrastructure Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#61]
Balboa Park Infrastructure Fee
Neighborhood-Specific

Planning Code Section 422
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_422

This fee addresses the impact on neighborhood infrastructure created by the increased development permitted under the Balboa Park Area Plan. It applies to all projects within the Balboa Park Area Plan and is triggered by (1) the addition of
a dwelling unit or (2) the addition or conversion of 800 square feet or more. In the case of a change of use, fees are lowered to provide credit for the existing use. There are additional options for compliance with this fee, including in-kind provision of infrastructure.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area expert: Jeff Horn
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
Corey, Jeff and Sylvia reported that the fee is calculating correctly.
