### ISSUE TITLE
Add Fee Type: Downtown Park Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#62]
Downtown Park Fee
Neighborhood-specific

Planning Code Section 412
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_412

This fee addresses the impact created by office uses on down- town parks. It applies to office uses in C-3 Zoning Districts and is triggered by any addition of, or conversion to, office space.

**Comment by ryan86** [comment]
@mikewynne 

This fee references the C-3-O, C-3-O (SD), C-3-R, C-3-G or C-3-S Use Districts. Are those district geometries available to us via a map service - maybe via the downtown park fee map service?

**Comment by mikewynne** [comment]
@ryan86 The Downtown Park area seems to be much larger.  I just added a new layer to the ArcGIS Server map service called 'Downtown Zoning' which includes all of those C3 districts.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area expert: Nick Foster
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
Fee appears to calculate correctly.  But, multiple people are reporting that it does not trigger for parcels in the downtown area that are also in the Transit Center area (TC is a subset of the downtown area).

**Comment by ryan86** [comment]
@mikewynne the Downtown Zoning layer does not appear to include the Transit Center area. If the Transit Center area is added to the Downtown Zoning layer this fee should work correctly. Otherwise, I could add an intersection to this fee to include the Transit Center Area from the Neighborhood-Specific Impact Fee Areas layer. 

Let me know how you would like me to proceed.


http://g.recordit.co/Lx312DZZVC.gif

**Comment by mikewynne** [comment]
@ryan86 Hi Ryan, the area should be the Downtown Park Fee under the Neighborhood-Specific Impact Fee Areas layer, which includes the transit center area.  In the following screenshot it's the salmon colored area:
![downtown](https://user-images.githubusercontent.com/7946733/36705676-3f6fc2d2-1b1b-11e8-8497-6a189df5da99.PNG)

**Comment by mikewynne** [comment]
@ryan86 Thanks Ryan.  I don't see any reason that the Transit Center zoning district was excluded from the 'Downtown Zoning' layer so I just added it.  That means that the 'Downtown Zoning' and 'Downtown Zoning' layers should be almost identical. Ideally you would just use the 'Downtown Zoning' layer.  thanks, mike.

**Comment by ryan86** [comment]
Remove Downtown Park Fee layer in favor of using just the Downtown Zoning layer.

**Comment by mikewynne** [comment]
@ryan86 Thanks Ryan, the fee looks good.
