### ISSUE TITLE
Add Fee Type: Eastern Neighborhoods Infrastructure Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#63]
Eastern Neighborhoods Infrastructure Fee
Planning Code Section 423
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_423

This fee addresses the impact on neighborhood infrastructure created by the increased development permitted under the Eastern Neighborhoods Area Plan. It applies to all projects within the Eastern Neighborhoods Plan Area (East SoMa, Western SoMa, Showplace Square/Potrero Hill, the Mission, and Central Waterfront) and is triggered by (1) the addition of a dwelling unit or (2) the addition or conversion of 800 square feet or more of space. In the case of a change of use, fees are lowered to provide credit for the existing use. There are ad- ditional options for compliance with this fee, including in-kind provision of infrastructure.

**Comment by ryan86** [comment]
@mikewynne 

The first two have to do with the Tier designations from the legalese. The third is about the Urban Mixed Use service and the legalese.

1.) Are all changes of use assumed to be in an existing structure?

2.) What should we do about portioning of a project? As in 'only the residential portion of a project'.

3.) Should we use a specific Tier (A, B, C) of the Urban Mixed Use service hosted by the planners?

**Comment by mikewynne** [comment]
Hi @ryan86 You asked 3 questions earlier about this fee, here is a recap of the Q's and the answers I got from one of the planners (Doug).  Let me know if these aren't clear and we could perhaps set up a quick phone meeting with Doug.

Original questions:

1.) Are all changes of use assumed to be in an existing structure?
2.) What should we do about portioning of a project? As in 'only the residential portion of a project'.
3.) Should we use a specific Tier (A, B, C) of the Urban Mixed Use service?

Answers from Doug:
1.	Yes, all changes of use are associated with an existing structure that will likely (but not always) be demolished and established in a newly constructed building.
2.	I’m not exactly clear what you mean, but the residential component could be included on the same page as the non-residential, and should ask for existing and proposed amounts. For net new additions, there are only two categories, but for change/replacement of use, there are three that are not indexed annually. 
3.	For EN Impact Fee calculation in any UMU zoned property, the tier 1 fee should be used for the residential component, and tier 2 for the non-residential component (same as for net new additions). Tiers A, B ,& C under Section 419.3 only represents the higher affordable housing requirements in the UMU.

**Comment by adamlodge** [comment]
@mikewynne Did we decide that we are going to put this one in the icebox for now? If not, how does this prioritize relative to everything else that is currently in progress?

**Comment by mikewynne** [comment]
@adamlodge We are still getting pushed to get this one working, so definitely not in the Icebox.  It's actually the most important of the fees, although it is probably the most complicated.  Ideally we'd fix the fees in QA and also get this one working within the hours that we have left. If that's not possible then I'd say fixing the fees in QA takes priority.  But it's higher priority than the UI changes.

**Comment by robgaston** [comment]
@mikewynne I've merged this fee into `master`; it will trigger for any project w/in the EN area, but it only calculates a fee when the project area only intersects a single tier area.  The following tier areas are also not currently supported as per our discussion last week:

- Eastern Neighborhoods Infrastructure Impact Fee - Tier 1 for 45 feet. Tier 2 for 65 feet.
- Eastern Neighborhoods Infrastructure Impact Fee - Tier 1 for 65 feet. Tier 2 for 85 feet.
- Eastern Neighborhoods Infrastructure Impact Fee - Tier 1 for 45 and 55 feet. Tier 2 for 65 feet.

In these cases, or when the project area intersects no or multiple tier areas, the fee is triggered, but the report shows a warning saying that the fee could not be calculated.

**Comment by mikewynne** [comment]
1. There is no way in the UI to differentiate Change of Use from Replacement of Use.  Need to add a ‘Replacement of Use’ section to the trigger page as sometimes the rate is different.
2. "Could not determine fee tier" is displayed more often than expected.
3. Corey thought that the replacement fee was used instead of the change of use fee, this needs to be checked.
Otherwise the fee worked well - correctly calculated the fees for 100% new construction, 100% Change of Use and projects with a combination of both.

**Comment by mikewynne** [comment]
2. Above split off into separate issue and closed.
