### ISSUE TITLE
Add New Fee Type: Market & Octavia and Upper Market Street Affordable Housing Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#64]
Market & Octavia and Upper Market Street
Affordable Housing Fee
Planning Code Section 416
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_416

This fee addresses the impact created by new market-rate housing to the stock of, and need for, affordable housing within and nearby the Market and Octavia Plan Area. It applies in (1) the Market and Octavia Plan Area and (2) the Upper Market Neighborhood Commercial District and is triggered by the creation of 10 or more dwelling units. It applies in addition to the city-wide Affordable Housing Fee (discussed above). In the case of a change of use, fees are lowered to provide credit for the existing use.

**Comment by mikewynne** [comment]
@ryan86 
1.) They are different, I just added the Special Use District to the map service as a new layer.
2.) I'll check and get back to you...
3.) I just added a new layer for the NCT district to the map service.

**Comment by ryan86** [comment]
@mikewynne 

Thanks for those layers.

In looking at the SUD layer it doesn't look like there is a "Van Ness and Market Special Use District". 

I see the following that are close:
Van Ness
Van Ness Automotive
Van Ness Medical Use Subdistrict
Van Ness & Market Downtown Residential

**Comment by mikewynne** [comment]
@ryan86 
I'm pretty certain it's the last one - Van Ness and Market Downtown Residential

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen, Jeff Horn, Nick Foster  
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
The fee seems to be calculating correctly.  But, multiple people are reporting triggering issues - it only appears to be triggered for parcels where there are multiple fee areas at the location.  E.g. 2100 Market (there the fee area overlaps with the Upper Market NCT) it triggers correctly but 1699 Market (where this is the only fee area), it is not triggered.

**Comment by mikewynne** [comment]
![mo_screenthot](https://user-images.githubusercontent.com/7946733/35412468-24da16ce-01d1-11e8-824d-9dc2614ff2d6.PNG)

**Comment by mikewynne** [comment]
It looks like it's tied just to the Upper Market St NCT, when it should be triggered by any project in one or both of the Market and Octavia Affordable Housing Fee area and the Upper Market St NCT.

**Comment by ryan86** [comment]
should be resolved in the latest

**Comment by mikewynne** [comment]
@ryan86 Look good Ryan, thanks!
