### ISSUE TITLE
Add New Fee Type: Market & Octavia Infrastructure Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#65]
Market & Octavia Infrastructure Fee
Planning Code Section 421
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_421

This fee addresses the impact on neighborhood infrastructure created by the increased development permitted under the Market and Octavia Area Plan. It applies in the Market and Octavia Plan Area to all projects and is triggered by (1) the addition of a dwelling unit or (2) the addition or change of use of 800 square feet of space. In the case of a change of use, fees are lowered to provide credit for the existing use. There are additional options for compliance with this fee, including in-kind provision of infrastructure.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen 
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
Corey and Jeff reported that the fee is calculating correctly. Doug said the fee is incorrect.  I'll follow up with them.

**Comment by mikewynne** [comment]
The components of the fee are calculating correctly but the total is wrong.  Screenshot to follow.

**Comment by mikewynne** [comment]
![moinf](https://user-images.githubusercontent.com/7946733/35709469-7dfa30a4-0767-11e8-9635-f6069b943670.PNG)

**Comment by ryan86** [comment]
should be fixed in the latest

**Comment by mikewynne** [comment]
@ryan86 Looks perfect, thanks Ryan!
