### ISSUE TITLE
Add Fee Type: Rincon Hill Infrastructure Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#66]
Rincon Hill Infrastructure Fee
Planning Code Section 418
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_418

This fee addresses the impact on neighborhood infrastructure created by the increased development permitted under the Rincon Hill Area Plan. It applies to all projects in the Rincon Hill Plan Area and is triggered by (1) the addition of a dwelling unit or (2) the addition or change the use of 800 square feet
of space. In the case of a change of use, fees are lowered to provide credit for the existing use. There are additional options for compliance with this fee, including in-kind provision of infrastructure.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen 
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
The fee is calculating correctly. :)
