### ISSUE TITLE
Add Fee Type: South of Market Community Stabilization Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#67]
South of Market Community Stabilization Fee
Planning Code Section 418.3(d)
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_418.3

This fee addresses the impact on existing neighborhoods created by the increased development permitted under the Rincon Hill Area Plan. It applies in the Rincon Hill Plan Area and is triggered by any addition of residential square footage.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen 
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
This fee is calculating correctly.
