### ISSUE TITLE
Add Fee Type: Transit Center Transportation and Street Improvement Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#69]
Transit Center Transportation and Street Improvement Fee
Planning Code Section 424.7
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_424.7

This fee addresses the impact on the transportation system created by the increased development permitted under the Transit Center District Plan. It applies in addition to the Transit Impact Development Fee (TIDF) to all projects in the Transit Center Special Use District and is triggered by (1) the addition of a dwelling unit, (2) the addition of 800 square feet of space, or (3) the creation of any new use subject to higher fees than the use it replaces. Fees vary depending on use, with an increase for square footage beyond a Floor Area Ratio (FAR)
of 9:1 and a further increase for square footage beyond a Floor Area Ratio (FAR) of 18:1. There are additional options for com- pliance with this fee, including in-kind provision of infrastructure.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Nick Foster
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
Same two issues as the Transit Center OS Fee:

1. Under the calculate page all of the new addition types (retail, hotel, etc.) are listed but Office is not (because it's on the trigger page). This is confusing some users. Can we add Office to the calculate page and pre-populate it with the number entered in the trigger page?
2. The FAR > 9:1 and FAR > 18:1 proportioning does not appear to be working correctly, it's always appearing as N/A or 0 for the GSF. The FAR ratio should relate to the entire project - so if the whole project has a FAR > 9:1 then the FAR proportioning should occur.

**Comment by adamlodge** [comment]
saving for pair-programming at end of project.

**Comment by mikewynne** [comment]
Adding clarification for work session with @robgaston 

Once the entire project goes beyond a 9:1 FAR the proportioning kicks in.  E.g. a project on a 1,000 sq ft parcel with 8,000 sq ft of residential and 2,000 sq ft of office will result in the 9:1 threshold kicking in at 9,000 sq ft (90% being below the threshold and 10% being above).   It gets portioned out as 90% of the residential 9,000 sq ft being below the threshold (8,100) and being given the base fee and 10% (900) being given the higher (above FAR 9:1) fee.  Same with the office space - 90% (900 sq ft) applying to the base fee and 10% (100 sq ft) applying to the higher fee.

And, for really large projects with a FAR > 18:1 the second tier kicks in in a similar way.

**Comment by mikewynne** [comment]
Closing this fee, we think it's now correct although Corey feels that it won't be used again so suspending QAing and shifting to 'Closed'.
