### ISSUE TITLE
Add Fee Type: UMU District Affordable Housing Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#70]
UMU District Affordable Housing Fee
Planning Code Section 419
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_419

This fee addresses the impact created by new market-rate housing in formerly industrial areas to the stock of affordable housing. It applies in the UMU Zoning District instead of the Affordable Housing Fee that applies elsewhere in the City (discussed above), and is triggered by the addition of ten or more dwelling units. Generally between 23% and 27% of the number of new units, depending on the applicable Fee Tier, at a unit-size mix reflective of the overall project, are used as the basis for the fee. There are additional options for compliance with this fee, including providing on-site units, providing middle-income affordable units, and dedicated land for the future development of affordable housing.

NOTE: Affordable Housing fees may soon all change their logic (switching from unit based to square footage based), so hold off on these for now (don't start without confirmation on the logic change).

**Comment by mikewynne** [comment]
@robgaston I thought that we'd get by without building this one but the affordable housing group have asked for it to be built.  Generally, the logic is the same as the citywide Affordable Housing Fee #51, (arguably they are actually the same fee), but with different rates and slightly different triggers.  So the developer would just pay this fee or the #51 fee, so building out this may have some affect on the #51 fee.  The UMU tiers should be in the map service.  Thanks!

**Comment by adamlodge** [comment]
Mike,

Trying to gauge urgency of this.  Can these latest requests wait until the new year?

**Comment by mikewynne** [comment]
Yes!  I just sent an email to you and Rob.

Mike Wynne, Senior GIS Business Analyst
San Francisco Planning Department
1650 Mission Street, Suite 400 San Francisco, CA 94103
Direct: 415.575.9096 | www.sfplanning.org<http://www.sfplanning.org/>
San Francisco Property Information Map<http://propertymap.sfplanning.org/>

**Comment by robgaston** [comment]
@mikewynne i added this fee as part of the existing affordable housing fee (#51) here: #221

**Comment by mikewynne** [comment]
See comments on Inclusionary Affordable Housing Fee #51
