### ISSUE TITLE
Add Fee Type: Van Ness & Market Affordable Housing and Infrastructure Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#71]
Van Ness & Market Affordable Housing and Infrastructure Fee
Planning Code Section 424
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_424

This fee addresses the impact created by new development to the stock of, and need for, affordable housing and neighbor- hood infrastructure nearby the intersection of Market Street and Van Ness Avenue. It applies in the Van Ness and Market Downtown Residential Special Use District and is triggered
by any addition or new construction in excess of a Floor Area Ratio (FAR) of 6:1. It applies in addition to the city-wide Afford- able Housing Fee (discussed above). Fees vary depending
on use, and increase for square footage beyond a Floor Area Ratio (FAR) of 9:1. There are additional options for compliance with this fee, including in-kind improvements.

**Comment by robgaston** [comment]
@mikewynne could you please help us understand Floor Area Ratio (FAR) in this context?

Specifically, what information do we need to collect from the user to calculate "new construction in excess of a Floor Area Ratio (FAR) of 6:1", for instance?  And how do we do that calculation?

**Comment by mikewynne** [comment]
@robgaston That should be the FAR of the final project.  So, once the building has finished being built or extended a FAR of 6:1 would trigger the fee.  FAR is the building's floor space as a ratio of the parcel's surface area.  E.g. a building with a floor space of 60,000 sq ft on a parcel of 10,000 sq ft would have a FAR of 6:1.  We just need those 2 numbers to do the calculation (parcel area and building floor area).

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen 
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
The fee is using the wrong GSF for the FAR calculations - it should be calculating based on the net new GSF.  In the example below it should be using 50,000 GSF, not 60,000GSF.

https://sfcpc.github.io/ifc/?state=report&fees=%7B%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22soma-non-residential-open-space%22%3A%7B%22newManufacturing%22%3Anull%2C%22paySomaFee%22%3Anull%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGSF%22%3A%22450000%22%7D%2C%22citywide-childcare-residential%22%3A%7B%22percentCcCredit%22%3A%220%22%7D%7D&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13627594.927541285%2C4547583.461287709%5D%2C%5B-13627616.136019352%2C4547669.344479225%5D%2C%5B-13627620.541042916%2C4547707.577075543%5D%2C%5B-13627582.364802789%2C4547745.738971633%5D%2C%5B-13627508.010507386%2C4547670.712411409%5D%2C%5B-13627594.927541285%2C4547583.461287709%5D%5D%5D%7D&newUnits=50&removedUnits=0&existingUnits=0&newNonRes=00&nonResGSF=0&pdrGSF=0&resGSF=50000&changeOfUse=0&officeGSF=0&newRes=50000&nonResToRes=0&pdrToRes=0&pdrToNonRes=0&retailGSF=&hotelGSF=&institutionalGSF=&industrialGSF=&parcelArea=65000

**Comment by robgaston** [comment]
@mikewynne the 60,000 GSF in this case is the calculated GSF in excess of a FAR of 6:1 for the total GSF 450,000 (/65,000 parcel area).  Should we just be collecting a net new GSF value for this instead?

**Comment by robgaston** [comment]
@mikewynne or can net new GSF be calculated by summing the following?:
Increase in non‐residential (GSF) 
Increase in PDR (GSF) 
Increase in residential (GSF) 
Increase in office space (GSF)

**Comment by mikewynne** [comment]
@robgaston The fee is calculating correctly. One small label change though - under the calculate page, some planning staff were thinking that the 'Total Building GFA' was the existing building but it appears to be the proposed building.  So, please change the label to 'Total Proposed Building GFA'.  Thanks

**Comment by adamlodge** [comment]
@robgaston this fee didnt make it into my branch for updating to 2018 schedule.  Could you update readme and settings appropriately?  Relevant info is: ```$42.45 per net additional gsf for FAR between 6:1 and 9:1.```

**Comment by mikewynne** [comment]
@robgaston Hi Rob, I assigned this one back to you just to make the small change to the label  - 'Total Building GFA' to be changed to 'Total Proposed Building GFA' (see above for details).  Thanks.
