### ISSUE TITLE
Add Fee Type:  Bicycle Parking Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#73]
Bicycle Parking Fee
Planning Code Section 430
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_430

This fee addresses impacts to the City’s bicycle infrastructure from development projects that seek to not provide otherwise- required Class 2 bicycle parking spaces (e.g. short-term pub- licly accessible bicycle racks). It is available to any project that either (a) chooses to pay a fee rather than provide the required number of Class 2 spaces, within specific parameters or (b) receives a Variance or exception from providing the required number of Class 2 spaces beyond those parameters.

**Comment by robgaston** [comment]
@mikewynne we've begun work on this fee and as part of this we are calculating the total number of spaces required; however, based on the feedback we've gotten on the OS fees, I think it's worth asking if the fee calculator should even do this?

That is: should we just have the user enter the number of spaces for which they will pay the in-lieu fee and let the calculation of the number of spaces be done outside of the fee calculator (as it doesn't really have any bearing on the total fee calculation)?

**Comment by mikewynne** [comment]
@robgaston Yes, please do that.  Generally speaking we want the IFC to strictly do fee calculations and avoid doing any calculations that involve interpreting non-fee aspects of the Planning Code.  There are fuzzy boundaries between the two of course... :)
