### ISSUE TITLE
Add Fee Type: Downtown Special Development District Open Space Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#74]
Downtown Special Development District
Open Space Fee
Planning Code Section 427(b)
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_427

This fee addresses the impact on parks and open spaces from development projects that seek to not provide the otherwise-required on-site open space. It applies in the C- 3-O(SD) District to all projects that (a) receive a Variance from providing the required amount of residential Usable Open Space or (b) are required to provide Privately Owned Public Open Space (POPOS) but choose to pay a fee for some or all of that space.

**Comment by mikewynne** [comment]
Hey @robgaston it looks like this is using the fee ($1,410 per GFA) from the planning code.  It should be using the fee schedule (http://forms.sfplanning.org/Impact_Fee_Schedule.pdf) which shows $1,876 as the current fee.

**Comment by mikewynne** [comment]
@robgaston Thanks Rob!

**Comment by robgaston** [comment]
@mikewynne I've updated this fee to collect the shortfall of OS

**Comment by mikewynne** [comment]
Thanks @robgaston 

When I enter the shortfall it doesn't see that the fee is ready to calculate.  Maybe still be linked to the old variable...  In the attached PNG you can see that the "Next: View Report" button is still grayed out, even though the shortfall has been entered.

![ifc](https://user-images.githubusercontent.com/7946733/49038036-a31cb980-f170-11e8-806e-dbb9c15c3431.PNG)

**Comment by robgaston** [comment]
@mikewynne is it possible that you have something cached locally?  I'm not seeing this issue on my end, but the variable names did change on this field, which may be what's cached on your end

**Comment by mikewynne** [comment]
@robgaston This is good too.  Thanks.

**Comment by mikewynne** [comment]
@robgaston Hi Rob, can you check the triggering for this one - it seems to be triggering for all projects that we enter, it should only trigger for projects in the C-3-O(SD) zoning district.  Thanks

**Comment by robgaston** [comment]
@mikewynne this should be fixed in the latest.  Thanks!

**Comment by mikewynne** [comment]
@robgaston Hey Rob, I'm not able to get this one to trigger at all now.  Here's an example where it should be triggering (inside the C-3-O(SD)) but isn't appearing:

https://sfcpc.github.io/ifc/?state=calculate&fees=%7B%22affordable-housing%22%3A%7B%22ownershipType%22%3Anull%2C%22exemptFromAffordableHousingFee%22%3Anull%2C%22payEasternFee%22%3Anull%2C%22easternAffordableFee%22%3Anull%7D%2C%22bicycle-parking-in-lieu%22%3A%7B%22spacesInLieu%22%3A%220%22%7D%2C%22downtown-special-development-district-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22eastern-neighborhoods-infrastructure%22%3A%7B%22nonResToResEN%22%3Anull%2C%22pdrToResEN%22%3Anull%2C%22pdrToNonResEN%22%3Anull%2C%22nonResToResReplacement%22%3Anull%2C%22pdrToResReplacement%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22allAffordable%22%3Anull%7D%2C%22eastern-neighborhoods-non-residential-open-space%22%3A%7B%22pdrToNonResEN%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22retailOpenSpaceGFAShortfall%22%3Anull%2C%22manufacturingOpenSpaceGFAShortfall%22%3Anull%2C%22officeOpenSpaceGFAShortfall%22%3Anull%2C%22otherOpenSpaceGFAShortfall%22%3Anull%7D%2C%22eastern-neighborhoods-residential-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22citywide-childcare-hotel-office%22%3A%7B%22ccfGFA%22%3A%220%22%2C%22minCcfGFARequired%22%3A3000%2C%22totalProjGFA%22%3A30000%7D%2C%22jobs-housing-linkage%22%3A%7B%22newEnt%22%3A%220%22%2C%22newIntegratedPDR%22%3A%220%22%2C%22newResearchAndDevelopment%22%3A%220%22%2C%22newRetail%22%3A%220%22%2C%22newSmallEnterpriseWorkspace%22%3A%220%22%2C%22feeCredit%22%3A%220%22%2C%22oldPDRToEnt%22%3A%220%22%2C%22oldPDRToHotel%22%3A%220%22%2C%22oldPDRToOffice%22%3A%220%22%2C%22oldPDRToIntegratedPDR%22%3A%220%22%2C%22oldPDRToResearchAndDevelopment%22%3A%220%22%2C%22oldPDRToRetail%22%3A%220%22%2C%22oldPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22newPDRToEnt%22%3A%220%22%2C%22newPDRToHotel%22%3A%220%22%2C%22newPDRToOffice%22%3A%220%22%2C%22newPDRToIntegratedPDR%22%3A%220%22%2C%22newPDRToResearchAndDevelopment%22%3A%220%22%2C%22newPDRToRetail%22%3A%220%22%2C%22newPDRToSmallEnterpriseWorkspace%22%3A%220%22%2C%22resToEnt%22%3A%220%22%2C%22resToHotel%22%3A%220%22%2C%22resToOffice%22%3A%220%22%2C%22resToIntegratedPDR%22%3A%220%22%2C%22resToResearchAndDevelopment%22%3A%220%22%2C%22resToRetail%22%3A%220%22%2C%22resToSmallEnterpriseWorkspace%22%3A%220%22%7D%2C%22public-art%22%3A%7B%22constructionCost%22%3A%2220000%22%2C%22posRequirement%22%3Anull%2C%22nonResProject%22%3Anull%7D%2C%22citywide-childcare-residential%22%3A%7B%22newConstructionCredit%22%3Anull%2C%22changeOfUseCredit%22%3Anull%7D%2C%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22transportation-sustainability-fee%22%3A%7B%22exemptFromTSF%22%3Anull%2C%22nonResNonHealthGFA%22%3A%2230000%22%2C%22hospitalGFA%22%3A%220%22%2C%22healthGFA%22%3A%220%22%2C%22newNewHospitalBeds%22%3A%220%22%2C%22totalHospitalOperatorBeds%22%3A%220%22%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGFA%22%3Anull%7D%7D&title=&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13625080.733538436%2C4549464.8001004895%5D%2C%5B-13625125.484864287%2C4549510.128776644%5D%2C%5B-13625111.812938388%2C4549523.753617988%5D%2C%5B-13625084.469197905%2C4549551.003213328%5D%2C%5B-13625062.474247638%2C4549572.922560061%5D%2C%5B-13625054.051258368%2C4549564.393856636%5D%2C%5B-13625048.761578802%2C4549559.037625413%5D%2C%5B-13625038.060102193%2C4549548.201777368%5D%2C%5B-13625017.71512942%2C4549527.601076058%5D%2C%5B-13625039.71809469%2C4549505.674077455%5D%2C%5B-13625067.061835172%2C4549478.424741644%5D%2C%5B-13625080.733538436%2C4549464.8001004895%5D%5D%5D%7D&newUnits=10&removedUnits=0&existingUnits=0&newNonRes=30000&nonResGFA=20000&pdrGFA=0&resGFA=30000&changeOfUse=0&officeGFA=20000&hotelGFA=0&existingNonResGFA=0&finalBuildingHeight=20&totalExistingGFA=0&newRes=&nonResToRes=&pdrToRes=&pdrToNonRes=&retailGFA=&institutionalGFA=&industrialGFA=&parcelArea=

**Comment by robgaston** [comment]
@mike

**Comment by robgaston** [comment]
@mikewynne good catch - this should be fixed in the latest by #227 
Thanks!

**Comment by mikewynne** [comment]
@robgaston I'm only able to get it to trigger in one part of the C-3-O(SD) district.  See attached screenshot, it triggers in the part highlighted in yellow, but not in the larger area.
![capture](https://user-images.githubusercontent.com/7946733/52875737-ec462f00-3109-11e9-9657-a168e9918ddd.PNG)

**Comment by robgaston** [comment]
@mikewynne good catch - this should be fixed in `master` now (https://github.com/sfcpc/ifc/pull/228)

thanks!

**Comment by mikewynne** [comment]
Looks good, thanks @robgaston !
