### ISSUE TITLE
Add Fee Type: Eastern Neighborhoods Alternate Affordable Housing Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#75]
Eastern Neighborhoods Alternate Affordable Housing Fee
Planning Code Section 417
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_417

This fee addresses the impact created by new small-scale market-rate housing to the stock of, and need for, affordable housing. It is available to projects within the Eastern Neighbor- hoods Plan Area that create between 10 and 20 dwelling units, or no more than 25,000 square feet of residential space. Eligible projects can opt-out of the Affordable Housing Fee (discussed above) and instead choose to pay a rate based on the project’s total residential square footage.

NOTE: Affordable Housing fees may soon all change their logic (switching from unit based to square footage based), so hold off on these for now (don't start without confirmation on the logic change).

**Comment by mikewynne** [comment]
@robgaston There are only a maximum of 30 projects that will ever need to calculate this fee so the planners have asked for the trigger portion to be built out but not the fee logic.  For the calculate page can we just have a checkbox that the user must hit to say that they will calculate the fee manually and then have this also listed in the final report (that they agree to calculate it manually).  Thanks.

**Comment by robgaston** [comment]
@mikewynne just a thought... should we provide an input for the user to enter the manually calculated fee in addition to the checkbox that you describe?

**Comment by robgaston** [comment]
@mikewynne It sounds like in all cases, a developer will only pay one Affordable Housing Fee (either #51, #70, or #75).  I've started working on this fee (#75) and #71 as their own fees, but might it instead make more sense to just have a single Affordable Housing Fee that handles all three of these (and just applies the one relevant Affordable Housing Fee)? We could have the fee form and report reflect which fee is being applied.  What do you think?

**Comment by mikewynne** [comment]
I think either way is fine, as long as the final report states which one they are paying. So, if it makes it easier to build as 1 fee then that's totally fine.  It is kinda weird that they didn't just make them a single fee in the Planning Code.

**Comment by mikewynne** [comment]
@robgaston For your idea of providing an input for the user to enter the manually calculated fee - I like that!  Yes, please add it.

**Comment by robgaston** [comment]
@mikewynne i added this fee as part of the existing affordable housing fee (#51) here: #221
