### ISSUE TITLE
Add Fee Type: Eastern Neighborhoods Non-Residential Open Space Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#76]
Eastern Neighborhoods Non-Residential Open Space Fee
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_426

This fee addresses the impact on parks and open spaces from development projects that do not provide the otherwise- required on-site open space. It is available only in Eastern Neighborhoods Mixed Use Districts to non-residential projects that choose not to provide the required amount of Usable Open Space.

**Comment by robgaston** [comment]
@mikewynne this fee has been updated to simply collect the shortfall of OS; also I've updated w/ the latest fee schedule. Thanks!

**Comment by mikewynne** [comment]
@robgaston Looks good, thanks Rob!
