### ISSUE TITLE
Add Fee Type: Public Artwork Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#78]
Public Artwork Fee
Planning Code Section 429
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_429

This fee addresses impacts on arts and cultural resources from development projects that seek to not provide otherwise- required on-site public artwork. It is available to a subset of those projects which are required to install public art. Rather than providing on-site public art of a value equivalent to one percent of a project’s construction cost, projects may choose to pay a portion of that amount into the City’s Public Artwork Trust Fund.

**Comment by ryan86** [comment]
@mikewynne 

1) These features in the "Zoning Map - Zoning Districts" layer appear to have nothing in them: SLR, C-M. Additionally, do you have a layer that meets the requirements in 429.2b 2 and 3?

http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_429.2


2) What's the best way to determine whether a project requires a 'First Construction Document'? Can we determine this from other information (i.e. only new construction requires this) or would it be better to explicitly ask for this information on the trigger page?

http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_429.3

**Comment by mikewynne** [comment]
@ryan86  Hi Ryan, for 1. above, there will be times when there are zoning districts in the planning code that are currently not in the use (like SLR and C-M).  Please just build them into the logic in case they are used again (they'll then automatically appear in the Zoning Districts layer).  I'm working on creating a layer for 429.2b 3 and 3, I'll let you know when it's ready (hopefully tomorrow).

For 2. It's difficult to determine that, so let's just put a checkbox or something similar on the UI and let the planner select it if it applies.

**Comment by robgaston** [comment]
@mikewynne I've removed the "first construction document" checkbox and added the C-3 areas to the trigger area for this fee.  I am able to trigger this fee now, so I'm pretty sure those were the only problems outstanding, but please let me know.  Thanks!

**Comment by mikewynne** [comment]
@robgaston Hey Rob, I think it's only triggering in some of the C-3 districts.  E.g. the link below is using parcel 3708/095 which is in a C-3-O(SD) district (which is one of the range of C-3 districts), and it does not trigger. But if I change the parcel to 3706/276 (a C-3-R district) it then it does trigger.

The full set of C-3 districts all start with 'C-3, but if you need a full list then they are: C-3-G, C-3-O, C-3-O(SD), C-3-R, C-3-S.

https://sfcpc.github.io/ifc/?state=calculate&fees=%7B%22affordable-housing%22%3A%7B%22ownershipType%22%3Anull%7D%2C%22bicycle-parking-in-lieu%22%3A%7B%22spacesInLieu%22%3Anull%7D%2C%22downtown-special-development-district-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22eastern-neighborhoods-infrastructure%22%3A%7B%22nonResToResEN%22%3Anull%2C%22pdrToResEN%22%3Anull%2C%22pdrToNonResEN%22%3Anull%2C%22nonResToResReplacement%22%3Anull%2C%22pdrToResReplacement%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22allAffordable%22%3Anull%7D%2C%22eastern-neighborhoods-non-residential-open-space%22%3A%7B%22pdrToNonResEN%22%3Anull%2C%22pdrToNonResReplacement%22%3Anull%2C%22retailOpenSpaceGFAShortfall%22%3Anull%2C%22manufacturingOpenSpaceGFAShortfall%22%3Anull%2C%22officeOpenSpaceGFAShortfall%22%3Anull%2C%22otherOpenSpaceGFAShortfall%22%3Anull%7D%2C%22eastern-neighborhoods-residential-open-space%22%3A%7B%22openSpaceGFAShortfall%22%3Anull%7D%2C%22citywide-childcare-hotel-office%22%3A%7B%22ccfGFA%22%3Anull%2C%22minCcfGFARequired%22%3Anull%2C%22totalProjGFA%22%3Anull%7D%2C%22jobs-housing-linkage%22%3A%7B%22newEnt%22%3Anull%2C%22newIntegratedPDR%22%3Anull%2C%22newResearchAndDevelopment%22%3Anull%2C%22newRetail%22%3Anull%2C%22newSmallEnterpriseWorkspace%22%3Anull%2C%22feeCredit%22%3Anull%2C%22oldPDRToEnt%22%3Anull%2C%22oldPDRToHotel%22%3Anull%2C%22oldPDRToOffice%22%3Anull%2C%22oldPDRToIntegratedPDR%22%3Anull%2C%22oldPDRToResearchAndDevelopment%22%3Anull%2C%22oldPDRToRetail%22%3Anull%2C%22oldPDRToSmallEnterpriseWorkspace%22%3Anull%2C%22newPDRToEnt%22%3Anull%2C%22newPDRToHotel%22%3Anull%2C%22newPDRToOffice%22%3Anull%2C%22newPDRToIntegratedPDR%22%3Anull%2C%22newPDRToResearchAndDevelopment%22%3Anull%2C%22newPDRToRetail%22%3Anull%2C%22newPDRToSmallEnterpriseWorkspace%22%3Anull%2C%22resToEnt%22%3Anull%2C%22resToHotel%22%3Anull%2C%22resToOffice%22%3Anull%2C%22resToIntegratedPDR%22%3Anull%2C%22resToResearchAndDevelopment%22%3Anull%2C%22resToRetail%22%3Anull%2C%22resToSmallEnterpriseWorkspace%22%3Anull%7D%2C%22public-art%22%3A%7B%22constructionCost%22%3Anull%2C%22posRequirement%22%3Anull%2C%22nonResProject%22%3Anull%7D%2C%22citywide-childcare-residential%22%3A%7B%22newConstructionCredit%22%3Anull%2C%22changeOfUseCredit%22%3Anull%7D%2C%22soma-community-stabilization-fee%22%3A%7B%22totalRes%22%3Anull%7D%2C%22soma-non-residential-open-space%22%3A%7B%22newManufacturing%22%3Anull%2C%22paySomaFee%22%3Anull%7D%2C%22transportation-sustainability-fee%22%3A%7B%22exemptFromTSF%22%3Anull%2C%22nonResNonHealthGFA%22%3Anull%2C%22hospitalGFA%22%3Anull%2C%22healthGFA%22%3Anull%2C%22resToNonRes%22%3Anull%2C%22resToHealth%22%3Anull%2C%22resToHospital%22%3Anull%2C%22hospitalToRes%22%3Anull%2C%22hospitalToNonRes%22%3Anull%2C%22hospitalToPDR%22%3Anull%2C%22hospitalToHealth%22%3Anull%2C%22healthToRes%22%3Anull%2C%22healthToNonRes%22%3Anull%2C%22healthToPDR%22%3Anull%2C%22healthToHospital%22%3Anull%2C%22pdrToHealth%22%3Anull%2C%22pdrToHospital%22%3Anull%2C%22newNewHospitalBeds%22%3Anull%2C%22totalHospitalOperatorBeds%22%3Anull%7D%2C%22van-ness-market-infrastructure%22%3A%7B%22totalGFA%22%3Anull%7D%7D&title=&geometry=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-13625433.966758005%2C4549694.86221748%5D%2C%5B-13625410.145388855%2C4549670.912929471%5D%2C%5B-13625406.051057983%2C4549675.007655288%5D%2C%5B-13625405.5051472%2C4549675.553637635%5D%2C%5B-13625378.28096385%2C4549648.1828566855%5D%2C%5B-13625397.38817521%2C4549629.073964452%5D%2C%5B-13625419.770739943%2C4549606.68937515%5D%2C%5B-13625438.331929201%2C4549588.126536849%5D%2C%5B-13625489.377259064%2C4549639.445897802%5D%2C%5B-13625464.538095802%2C4549664.28775694%5D%2C%5B-13625452.25499187%2C4549676.572213132%5D%2C%5B-13625433.966758005%2C4549694.86221748%5D%5D%5D%7D&newUnits=100&removedUnits=0&existingUnits=0&newNonRes=0&nonResGFA=0&pdrGFA=0&resGFA=100000&changeOfUse=0&officeGFA=0&hotelGFA=0&existingNonResGFA=0&finalBuildingHeight=100&totalExistingGFA=0&newRes=&nonResToRes=&pdrToRes=&pdrToNonRes=&retailGFA=&institutionalGFA=&industrialGFA=&parcelArea=

**Comment by mikewynne** [comment]
@robgaston ...actually there is a layer in the map service for the C-3 districts - it's the one called 'Downtown Zoning'

**Comment by robgaston** [comment]
@mikewynne I've added that layer to the area check for this fee and it now triggers for the entire downtown zoning area.

Let me know if there are any other tweaks needed here.

Thanks!

**Comment by mikewynne** [comment]
@robgaston Looks good, thanks Rob!  I just met with Corey, he said to say thanks for all the great work you've been doing!
