### ISSUE TITLE
Add Fee Type: South of Market Non-Residential Open Space Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#79]
South of Market Non-Residential Open Space Fee
Planning Code Section 425
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_425

This fee addresses the impact on parks and open spaces from development projects that seek to not provide the otherwise-required on-site open space. It is available only in South of Market Mixed Use Districts to projects that choose not to provide the required amount of Usable Open Space.

FEE BEING RETIRED. This fee will be retired when the Central SoMa plan is adopted, so we won't need this fee.

**Comment by jmunowitch** [comment]
@mikewynne: I am currently using the _Eastern Neighborhoods Infrastructure Impact Fee_ area, but this doesn't seem quite right by my interpretation of the Planning Code.

Can you confirm the correct area? If it is not (and I don't think it is), we will need to add the new area to  AGS service.

**Comment by jmunowitch** [comment]
Pulled in with https://github.com/sfcpc/ifc/pull/103

**Comment by mikewynne** [comment]
@jmunowitch I think you are correct, the boundary appears to be missing from our GIS data.  I'll track it down and let you know once it's added to the AGS service.

**Comment by mikewynne** [comment]
@jmunowitch This one is based on zoning rather than plan areas so I created a new layer in the AGS service called SoMa Mixed Use Districts.

**Comment by mikewynne** [comment]
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen 
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment]
Since this is an Elective fee, let's move this into the Icebox.

**Comment by adamlodge** [comment]
Closing because it's either out of scope of the IFC or about to be retired.  Can be reopened if this changes.
